### ISSUE TITLE
Meal Algorithms

### ISSUE THREAD

**Issue by DanieSegarra36** [automeal/AutoMeal#40]
Carb and fat algos

**Comment by savannahnester** [comment]
In the survey if the user chooses a low-carb diet, the amount of carbs they can have per meal is:
maxCarb = maxCalories * .20 / numberOfMeals
where maxCalories is the maximum calorie value they set in their survey
and numberOfMeals is the number of meals they decide they want in their survey

**Comment by savannahnester** [comment]
In the survey if the user chooses a low-fat diet, the amount of fat they can have per meal is:
maxFat = maxCalories * .15 / numberOfMeals
where maxCalories is the maximum calorie value they set in their survey
and numberOfMeals is the number of meals they decide they want in their survey
