### ISSUE TITLE
Mobile view does not allow you to sign out

### ISSUE THREAD

**Issue by DanieSegarra36** [automeal/AutoMeal#49]
![img](https://media.giphy.com/media/l17MAP0HpmKRj2PgL8/giphy.gif)

Can't sign out on smaller screens and components would look better stacked

- [x] Allow components to stack
- [x] Display `Sign Out` on `MobileContainer` when user is logged in

**Comment by DanieSegarra36** [comment]
```
<Grid stackable columns="equal">
```

**Comment by toriasima** [comment]
Oops, I don't think I pushed my updates, will do now. But also the mobile menu issue (for logging out and other stuff) doesn't work on the home page and landing page. Likely because of the header image or something... WILL TRY TO FIX!!!

**Comment by DanieSegarra36** [comment]
@toriasima The PR [displaying recipe results](50) will have it the fix but feel free to add it to your code as well to test it out and see if any other issues need arise that require our attention
