### ISSUE TITLE
Generate Weekly Meal Plan

### ISSUE THREAD

**Issue by DanieSegarra36** [automeal/AutoMeal#66]
Have some sort of function to generate as many recipes as per day for the user and then do that seven times to generate meal plan

Any other suggestions are welcome

**Comment by savannahnester** [comment]
edit meal plan options (new random recipe, delete meal, search for recipe for meal plan)

**Comment by savannahnester** [comment]
It seems like the meal plan can be generated, but for the weekly meal plan you need to click "generate meal plan" 7 times in order to get a plan for every day of the week. Is someone currently working on fixing this?
