### ISSUE TITLE
Update User Info

### ISSUE THREAD

**Issue by savannahnester** [automeal/AutoMeal#68]
Functionality to change:
- [x] name
- [x] email
- [ ] diet (low carb/low fat)

Heroku currently has frontend portion to edit user info but it doesn't actually update it

**Comment by toriasima** [comment]
The latest merge to master should have added functionality for updating user info! I just tried on Heroku and was able to edit my name :o But I dunno about changing the diet

**Comment by DanieSegarra36** [comment]
![update user info](https://media.giphy.com/media/fQSl1JXdkgbUdWfWmG/giphy.gif)

It's working on [heroku](https://automeal.herokuapp.com)

I closed the page and when I returned it was updated
